# Generated by Django 5.0.3 on 2024-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hide_amount',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='hide_name',
            field=models.BooleanField(),
        ),
    ]
